## packages

```{r}
library(tidyverse)
library(lubridate)
library(conflicted)
library(rvest)
library(tidybayes)
library(progress)
conflict_prefer("filter", "dplyr")
conflict_prefer("lag", "dplyr")
source("functions.R")
```

need to get prior needed for the league I'm actually running (there might be more than one)

## get general stuff

```{r}
action2 <- read_rds("../ratings/action2.rds")
action2
games <- read_rds("../scoresway/rds/games.rds")
league_ids <- read_rds("../ratings/league_ids.rds")
rating_ranks <- read_rds("../ratings/rating_ranks.rds") # this is the only place to get team names from
league_ids %>% 
  mutate(r = row_number()) %>% 
  unnest(id) %>% 
  left_join(action2, by = "the_country") %>% 
  arrange(desc(to_rate), next_rate, get_games) -> league_ids
league_ids %>% select(the_country, last_rate, next_rate, day_of, to_rate, get_games) %>% 
  arrange(desc(last_rate))
```

```{r}
check_games <- function(row_number, league_ids, games) {
  league_ids %>% filter(r == row_number) %>% pull(id) -> idd
    games %>% filter(comp == idd) %>% 
    pivot_longer(matches("[12]_name")) %>%
    select(country, match, name, value) %>% 
    count(country, value) %>% arrange(desc(n)) -> d
  d %>%  summarize(country = min(country), m = mean(n), s = sd(n))
}
```

```{r}
check_games(5, league_ids, games)
```


check all rateable leagues



```{r}
league_ids %>%
  # filter(to_rate == "rateable") %>%
  mutate(rrr = row_number()) %>% 
  select(rrr, the_country, last_rate, next_rate, get_games, rem_games)
```



## pick a league (and get prior year)




```{r}
row_of_this <- 67
comp_no <- 1
check_league(row_of_this, league_ids, comp_no)
# walk(1:3, ~check_league(., league_ids, comp_no))
```

## count games by team pair

```{r}
league_id <- league_ids$row[row_of_this]
league_ids %>% filter(r == league_id) %>% pull(id) -> idd
games %>% filter(comp == idd) %>% 
  count(t1_name, t2_name)
```



