packages

```{r}
library(tidyverse)
library(conflicted)
library(rvest)
library(tidybayes)
conflict_prefer("filter", "dplyr")
source("functions.R")
```

get general stuff

```{r}
games <- read_rds("../scoresway/rds/games.rds")
league_ids <- readRDS("~/Documents/r-projects/ratings/league_ids.rds")
league_id <- 18
country_list <- get_country(league_id, league_ids) 
comp <- country_list$comps[1]
league_table <- get_league_table(country_list$comp) # have to get comp
league_table
```

check league table

```{r}
summary <- season_summary(comp, games, league_table)
summary
if (summary$s > 0) stop("teams have different #games")
season_games <- summary$m
season_games
```


```{r}
draws <- get_draws(country_list)
draws
```

match this up with teams and league standings

```{r}
lookup <- get_lookup(country_list)
basis <- get_basis(league_table, lookup)
basis
```

```{r}
games_left <- get_games_left(comp, games)
simulated <- sim_games(games_left, lookup, country_list)
simulated # data has id1 id2 (stan ids), sc1, sc2
```

```{r}
simulated
```



```{r}
simulated %>% 
  ungroup() %>% 
  rowwise() %>% 
  mutate(simtab = list(simulated_table(data, basis))) %>% 
  mutate(rk = list(simulated_rank(simtab))) -> d
d %>% unnest(rk) %>% 
  group_by(team_id) %>% 
  count(rank) %>% 
  mutate(cum_n = cumsum(n)) -> dd
# save this and then consult by colour
dd %>% 
  filter(rank<=24) %>% 
  group_by(team_id) %>% 
  filter(rank==max(rank)) %>% 
  arrange(desc(cum_n), rank)%>% 
  left_join(lookup, by = c("team_id" = "sw_id")) %>% 
  select(name, rank, cum_n)
```




