## packages

```{r}
library(tidyverse)
library(lubridate)
library(conflicted)
library(rvest)
library(tidybayes)
library(progress)
conflict_prefer("filter", "dplyr")
conflict_prefer("lag", "dplyr")
source("functions.R")
```

need to get prior needed for the league I'm actually running (there might be more than one)

## get general stuff

```{r}
action2 <- read_rds("../ratings/action2.rds")
action2
games <- read_rds("../scoresway/rds/games.rds")
league_ids <- read_rds("../ratings/league_ids.rds")
rating_ranks <- read_rds("../ratings/rating_ranks.rds") # this is the only place to get team names from
league_ids %>% 
  mutate(r = row_number()) %>% 
  unnest(id) %>% 
  left_join(action2, by = "the_country") %>% 
  arrange(desc(to_rate), next_rate, get_games) -> league_ids
league_ids 
```

```{r}
get_league_table(63612)
```

```{r}
  country_list <- get_country(22, league_ids, 2021) 
country_list
  league_table <- get_league_table(63602, 2) 
  league_table
  lookup <- get_lookup(country_list)
  lookup
  print(glue::glue("Got lookup."))
  basis <- get_basis(league_table, lookup)
basis
```

